name: Deploy

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: insd47
  DOCKERHUB_REPO: stocktree-frontend
  DOCKERHUB_REPO_TAG: latest
  EC2_USERNAME: ubuntu
  EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
  COMPOSE_DIRECTORY: ~/stocktree
  COMPOSE_SERVICE: frontend

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Next.js App
        run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$DOCKERHUB_REPO_TAG .
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$DOCKERHUB_REPO_TAG

      - name: Setting up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Service
        run: |
          ssh -o StrictHostKeyChecking=no -T $EC2_USERNAME@$EC2_INSTANCE_IP << EOF
            cd $COMPOSE_DIRECTORY
            sudo docker compose pull $COMPOSE_SERVICE
            sudo doppler run -- docker compose up -d $COMPOSE_SERVICE
          EOF
